on:
  pull_request:
name: Unit tests

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: "-mod=vendor"
    strategy:
      matrix:
        target:
          - check-docs
          - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install dependencies
        run: make setup
      - name: make ${{ matrix.target }}
        run: make ${{ matrix.target }}
